#!/usr/bin/env bash
#-- Requirements ---------------------------------------------------------------------------------------------------------------
command -v jq     >/dev/null 2>&2 || { echo >&2 "jq is required but is not available, aborting...";     exit 1; }
command -v docker >/dev/null 2>&2 || { echo >&2 "docker is required but is not available, aborting..."; exit 1; }

#-- Imported Variables ---------------------------------------------------------------------------------------------------------
target=$1
if [ -z "${target}" ]; then ls config/secrets && read -rp "Which environment would you like to target? Type your full answer here and press enter: " target; fi

network_name=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.network_name')

# ---- Create network for inter-container communication ------------------------------------------------------------------------
network_id=$(sudo docker network inspect --format='{{.Id}}' "${network_name}" 2> /dev/null)

if [ -z "${network_id}" ]; then
  echo "Network ${network_name} does not exist, creating it now."
  sudo docker network create "${network_name}"
fi
